import type { ParticlePreset } from "./particleTypes.ts";

const BASIC_DURATION_MS = 360;
const SKILL_DURATION_MS = 520;
const ULTIMATE_DURATION_MS = 900;

export const REQUIRED_PARTICLE_VFX_KEYS = [
  "red_skill_slash",
  "blue_skill_freeze",
  "yellow_skill_chain",
  "green_skill_shield",
  "purple_skill_bomb",
  "orange_skill_hammer",
  "red_ultimate_spin",
  "blue_ultimate_icefall",
  "yellow_ultimate_meteor",
  "green_ultimate_bloom",
  "purple_ultimate_magic_circle",
  "orange_ultimate_judgement",
] as const;

export const particlePresets = {
  generic_particle: preset({
    key: "generic_particle",
    color: "#ffffff",
    tone: "generic",
    level: "fallback",
    cssClass: "particle-generic-spark",
    durationMs: BASIC_DURATION_MS,
    size: 14,
    projectile: true,
    burst: true,
    aura: false,
    flash: true,
    burstCount: 6,
    priority: 4,
    target: "enemy",
    auraTarget: "battle",
    maxParticles: 6,
  }),
  yizai_basic_hit: preset({
    key: "yizai_basic_hit",
    color: "#fff2a8",
    tone: "yellow",
    level: "basic",
    cssClass: "particle-basic-hit",
    durationMs: BASIC_DURATION_MS,
    size: 12,
    projectile: true,
    burst: true,
    aura: false,
    flash: true,
    burstCount: 6,
    priority: 8,
    target: "enemy",
    auraTarget: "battle",
    maxParticles: 6,
  }),
  enemy_attack_hit: preset({
    key: "enemy_attack_hit",
    color: "#ffb15f",
    tone: "orange",
    level: "basic",
    cssClass: "particle-enemy-hit",
    durationMs: BASIC_DURATION_MS,
    size: 12,
    projectile: true,
    burst: true,
    aura: false,
    flash: true,
    burstCount: 6,
    priority: 8,
    target: "player",
    auraTarget: "battle",
    maxParticles: 6,
  }),
  skill_charge: preset({
    key: "skill_charge",
    color: "#8fd7ff",
    tone: "blue",
    level: "skill",
    cssClass: "particle-skill-charge",
    durationMs: SKILL_DURATION_MS,
    size: 18,
    projectile: false,
    burst: false,
    aura: true,
    flash: true,
    burstCount: 0,
    priority: 12,
    target: "player",
    auraTarget: "player",
    maxParticles: 20,
  }),
  skill_projectile: preset({
    key: "skill_projectile",
    color: "#8fd7ff",
    tone: "blue",
    level: "skill",
    cssClass: "particle-skill-projectile",
    durationMs: SKILL_DURATION_MS,
    size: 18,
    projectile: true,
    burst: true,
    aura: false,
    flash: true,
    burstCount: 12,
    priority: 14,
    target: "enemy",
    auraTarget: "battle",
    maxParticles: 20,
  }),
  ultimate_charge: preset({
    key: "ultimate_charge",
    color: "#ffe36e",
    tone: "yellow",
    level: "ultimate",
    cssClass: "particle-ultimate-charge",
    durationMs: ULTIMATE_DURATION_MS,
    size: 28,
    projectile: false,
    burst: false,
    aura: true,
    flash: true,
    burstCount: 0,
    priority: 24,
    target: "battle",
    auraTarget: "battle",
    maxParticles: 40,
  }),
  ultimate_burst: preset({
    key: "ultimate_burst",
    color: "#ffe36e",
    tone: "yellow",
    level: "ultimate",
    cssClass: "particle-ultimate-burst",
    durationMs: ULTIMATE_DURATION_MS,
    size: 30,
    projectile: false,
    burst: true,
    aura: true,
    flash: true,
    burstCount: 30,
    priority: 26,
    target: "enemy",
    auraTarget: "battle",
    maxParticles: 40,
  }),
  red_skill_slash: preset({
    key: "red_skill_slash",
    color: "#ff4a2f",
    tone: "red",
    level: "skill",
    cssClass: "particle-red-flame-slash",
    durationMs: 420,
    size: 18,
    projectile: true,
    burst: true,
    aura: false,
    flash: true,
    burstCount: 12,
    priority: 16,
    target: "enemy",
    auraTarget: "battle",
    maxParticles: 20,
  }),
  blue_skill_freeze: preset({
    key: "blue_skill_freeze",
    color: "#6ed6ff",
    tone: "blue",
    level: "skill",
    cssClass: "particle-blue-ice-crystal",
    durationMs: 520,
    size: 17,
    projectile: true,
    burst: true,
    aura: false,
    flash: true,
    burstCount: 12,
    priority: 16,
    target: "enemy",
    auraTarget: "battle",
    maxParticles: 20,
  }),
  yellow_skill_chain: preset({
    key: "yellow_skill_chain",
    color: "#ffd84d",
    tone: "yellow",
    level: "skill",
    cssClass: "particle-yellow-star-chain",
    durationMs: 500,
    size: 17,
    projectile: true,
    burst: true,
    aura: false,
    flash: true,
    burstCount: 14,
    priority: 16,
    target: "enemy",
    auraTarget: "battle",
    maxParticles: 20,
  }),
  green_skill_shield: preset({
    key: "green_skill_shield",
    color: "#43d17d",
    tone: "green",
    level: "skill",
    cssClass: "particle-green-shield",
    durationMs: 560,
    size: 20,
    projectile: true,
    burst: false,
    aura: true,
    flash: true,
    burstCount: 8,
    priority: 16,
    target: "player",
    auraTarget: "player",
    maxParticles: 20,
  }),
  purple_skill_bomb: preset({
    key: "purple_skill_bomb",
    color: "#a978ff",
    tone: "purple",
    level: "skill",
    cssClass: "particle-purple-orb",
    durationMs: 540,
    size: 19,
    projectile: true,
    burst: true,
    aura: false,
    flash: true,
    burstCount: 14,
    priority: 16,
    target: "enemy",
    auraTarget: "battle",
    maxParticles: 20,
  }),
  orange_skill_hammer: preset({
    key: "orange_skill_hammer",
    color: "#ff9d3b",
    tone: "orange",
    level: "skill",
    cssClass: "particle-orange-impact",
    durationMs: 500,
    size: 21,
    projectile: true,
    burst: true,
    aura: false,
    flash: true,
    burstCount: 16,
    priority: 16,
    target: "enemy",
    auraTarget: "battle",
    maxParticles: 20,
  }),
  red_ultimate_spin: preset({
    key: "red_ultimate_spin",
    color: "#ff2a1f",
    tone: "red",
    level: "ultimate",
    cssClass: "particle-red-ultimate-fire",
    durationMs: ULTIMATE_DURATION_MS,
    size: 28,
    projectile: true,
    burst: true,
    aura: true,
    flash: true,
    burstCount: 34,
    priority: 28,
    target: "enemy",
    auraTarget: "battle",
    maxParticles: 40,
  }),
  blue_ultimate_icefall: preset({
    key: "blue_ultimate_icefall",
    color: "#57c8ff",
    tone: "blue",
    level: "ultimate",
    cssClass: "particle-blue-ultimate-ice",
    durationMs: ULTIMATE_DURATION_MS,
    size: 28,
    projectile: true,
    burst: true,
    aura: true,
    flash: true,
    burstCount: 32,
    priority: 28,
    target: "enemy",
    auraTarget: "battle",
    maxParticles: 40,
  }),
  yellow_ultimate_meteor: preset({
    key: "yellow_ultimate_meteor",
    color: "#ffd84d",
    tone: "yellow",
    level: "ultimate",
    cssClass: "particle-yellow-ultimate-meteor",
    durationMs: ULTIMATE_DURATION_MS,
    size: 28,
    projectile: true,
    burst: true,
    aura: true,
    flash: true,
    burstCount: 34,
    priority: 28,
    target: "enemy",
    auraTarget: "battle",
    maxParticles: 40,
  }),
  green_ultimate_bloom: preset({
    key: "green_ultimate_bloom",
    color: "#34d399",
    tone: "green",
    level: "ultimate",
    cssClass: "particle-green-ultimate-bloom",
    durationMs: ULTIMATE_DURATION_MS,
    size: 30,
    projectile: true,
    burst: true,
    aura: true,
    flash: true,
    burstCount: 28,
    priority: 28,
    target: "player",
    auraTarget: "player",
    maxParticles: 40,
  }),
  purple_ultimate_magic_circle: preset({
    key: "purple_ultimate_magic_circle",
    color: "#9f6cff",
    tone: "purple",
    level: "ultimate",
    cssClass: "particle-purple-ultimate-circle",
    durationMs: ULTIMATE_DURATION_MS,
    size: 30,
    projectile: true,
    burst: true,
    aura: true,
    flash: true,
    burstCount: 34,
    priority: 28,
    target: "enemy",
    auraTarget: "battle",
    maxParticles: 40,
  }),
  orange_ultimate_judgement: preset({
    key: "orange_ultimate_judgement",
    color: "#ff9d3b",
    tone: "orange",
    level: "ultimate",
    cssClass: "particle-orange-ultimate-judgement",
    durationMs: ULTIMATE_DURATION_MS,
    size: 30,
    projectile: true,
    burst: true,
    aura: true,
    flash: true,
    burstCount: 36,
    priority: 28,
    target: "enemy",
    auraTarget: "battle",
    maxParticles: 40,
  }),
} as const satisfies Record<string, ParticlePreset>;

export type ParticlePresetKey = keyof typeof particlePresets;

export function getParticlePreset(key: string): ParticlePreset {
  return particlePresets[key as ParticlePresetKey] ?? particlePresets.generic_particle;
}

export function getBattleParticleKey(keys: readonly string[]): string | undefined {
  return keys.find(
    (key) =>
      !key.startsWith("screenShake:") &&
      !key.startsWith("skillText:") &&
      !key.startsWith("combo:"),
  );
}

function preset(value: ParticlePreset): ParticlePreset {
  return value;
}
