export const PRESENTATION_TIMING = {
  NORMAL_TURN_MAX_MS: 900,
  SKILL_TURN_MAX_MS: 1200,
  ULTIMATE_TURN_MAX_MS: 1500,
  ULTIMATE_TURN_HARD_CAP_MS: 1600,
  ENEMY_ATTACK_MS: 640,
  ENEMY_ATTACK_LOCK_MAX_MS: 700,
  WAVE_TRANSITION_MS: 600,
  WAVE_TRANSITION_MAX_MS: 800,
  HP_TWEEN_MS: 180,
  DAMAGE_TEXT_MS: 600,
  RESHUFFLE_NOTICE_MS: 800,
  BOARD_CLEAR_MS: 220,
  NORMAL_HIT_MS: 260,
  SKILL_HIT_MS: 350,
  ULTIMATE_HIT_MS: 400,
} as const;

export type PresentationTiming = typeof PRESENTATION_TIMING;
